services:
  vdm:
    image: whyaydan/discord_vdm:latest
    restart: unless-stopped
    enviroment:
      - AUTHORS=""
      - ROLE=""
      - DISCORD_TOKEN=""
    volumes:
      -  database:/app/database
volumes:
  database: