services:
  at:
    image: whyaydan/discord_vdm
    restart: unless-stopped
    environment:
      - authors=redacted
      - role=redacted
      - token=redacted
     volumes:
      - /some/database/directory:/database
