version: '3'

services:
  vdm:
    image: whyaydan/discord_vdm
    restart: unless-stopped
    environment:
      - AUTHORS=""
      - ROLE=""
      - DISCORD_TOKEN=“”
    volumes:
      - /database:/database
